package model

// PrepResponse is a struct that represents the response from the ICON tracker API.
type PrepResponse struct {
	NodeAddress               string  `json:"node_address"`
	LastUpdatedTimestamp      *string `json:"last_updated_timestamp,omitempty"`
	YouTube                   string  `json:"youtube"`
	Wechat                    string  `json:"wechat"`
	Delegated                 float64 `json:"delegated"`
	Bonded                    float64 `json:"bonded"`
	RewardDaily               float64 `json:"reward_daily"`
	MaxCommissionRate         float64 `json:"max_commission_rate"`
	Name                      string  `json:"name"`
	PublicKey                 string  `json:"public_key"`
	CreatedBlock              int     `json:"created_block"`
	Facebook                  string  `json:"facebook"`
	ApiEndpoint               string  `json:"api_endpoint"`
	Stake                     float64 `json:"stake"`
	Power                     float64 `json:"power"`
	RewardDailyUSD            float64 `json:"reward_daily_usd"`
	CommissionRate            float64 `json:"commission_rate"`
	Address                   string  `json:"address"`
	NodeState                 string  `json:"node_state"`
	CreatedTimestamp          *string `json:"created_timestamp,omitempty"`
	Github                    string  `json:"github"`
	MetricsEndpoint           string  `json:"metrics_endpoint"`
	Irep                      float64 `json:"irep"`
	SponsoredCpsGrants        *string `json:"sponsored_cps_grants,omitempty"`
	Stakers                   int     `json:"stakers"`
	MinDoubleSignHeight       *string `json:"min_double_sign_height,omitempty"`
	Country                   string  `json:"country"`
	Status                    string  `json:"status"`
	Logo256                   string  `json:"logo_256"`
	P2PEndpoint               string  `json:"p2p_endpoint"`
	ServerCity                string  `json:"server_city"`
	IrepUpdatedBlockHeight    *string `json:"irep_updated_block_height,omitempty"`
	CpsGovernance             bool    `json:"cps_governance"`
	Bonders                   int     `json:"bonders"`
	HasPublicKey              bool    `json:"has_public_key"`
	City                      string  `json:"city"`
	Penalty                   string  `json:"penalty"`
	Logo1024                  string  `json:"logo_1024"`
	Reddit                    string  `json:"reddit"`
	ServerCountry             string  `json:"server_country"`
	TotalBlocks               float64 `json:"total_blocks"`
	FailureCount              int     `json:"failure_count"`
	JailFlags                 *string `json:"jail_flags,omitempty"`
	Email                     string  `json:"email"`
	Grade                     string  `json:"grade"`
	LogoSVG                   string  `json:"logo_svg"`
	Keybase                   string  `json:"keybase"`
	ServerType                string  `json:"server_type"`
	ValidatedBlocks           float64 `json:"validated_blocks"`
	Penalties                 int     `json:"penalties"`
	UnjailRequestHeight       *string `json:"unjail_request_height,omitempty"`
	Website                   string  `json:"website"`
	LastUpdatedBlock          int     `json:"last_updated_block"`
	Steemit                   string  `json:"steemit"`
	Telegram                  string  `json:"telegram"`
	Voted                     float64 `json:"voted"`
	UnvalidatedSequenceBlocks *string `json:"unvalidated_sequence_blocks,omitempty"`
	RewardMonthly             float64 `json:"reward_monthly"`
	MaxCommissionChangeRate   float64 `json:"max_commission_change_rate"`
	Details                   string  `json:"details"`
	Twitter                   string  `json:"twitter"`
	VotingPower               float64 `json:"voting_power"`
	RewardMonthlyUSD          float64 `json:"reward_monthly_usd"`
}
