name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
    CI:
      runs-on: ubuntu-latest

      permissions:
        contents: write
      steps:
        - uses: actions/checkout@master
        - uses: go-semantic-release/action@v1
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}